### ISSUE TITLE
OpenAudible 1.1.4 won't connect in Ubuntu 18.04

### ISSUE THREAD

**Issue by livtin** [chipaudette/OpenAudio#4]
I just did a clean install of Ubuntu 18.04 and tried to install OpenAudible.  The original version I installed will not uninstall and the new version will not connect to audible.  The program accepts my login and password in preferences and opens the web page for the login page BUT it still indicates Connected No.

**Comment by chipaudette** [comment]
Umm...I'm confused.  You're leaving this message on my repo named OpenAudio.  This is not OpenAudible.  If you're looking for OpenAudible, you will want to go over to that repo, not mine...
